# Generated by Django 5.0.7 on 2024-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.JSONField(max_length=128),
        ),
    ]
