# Generated by Django 5.0.7 on 2024-07-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_contact_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
    ]
